laser_roll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: laser_roll_joint
    joint_speed: 0.5
    motor:
        id: 2
        init: 512
        min: 415
        max: 610

laser_pitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: laser_pitch_joint
    joint_speed: 0.5
    motor:
        id: 1
        init: 512
        min: 445
        max: 610

kinect_pitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: kinect_pitch_joint
    joint_speed: 0.5
    motor:
        id: 3
        init: 512
        min: 420
        max: 715

kinect_yaw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: kinect_yaw_joint
    joint_speed: 1.0
    motor:
        id: 4
        init: 512
        min: 370
        max: 715

linear_head_pitch_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: linear_head_pitch_joint
    joint_speed: 0.5
    motor:
        id: 6
        init: 512
        min: 415
        max: 650

linear_head_yaw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: linear_head_yaw_joint
    joint_speed: 0.5
    motor:
        id: 5
        init: 512
        min: 310
        max: 715
