power_supplies:
  - name: '/PSU_battery'
    max_voltage: 24.0
  - name: '/motors_battery'
    max_voltage: 24.0
range_sensors:
  - name: 'default_sonar'
    frame_id: ''
    radiation_type: 0
    field_of_view: 80.0
    min_range: 0.2
    max_range: 4.5
    i2c_address: -1
  - name: 'default_ir'
    frame_id: ''
    radiation_type: 1
    field_of_view: 8.5
    min_range: 0.1
    max_range: 0.6
    i2c_address: -1
  - name: '/sensors/left_sonar'
    frame_id: '/left_sonar'
    radiation_type: 0
    field_of_view: 80.0
    min_range: 0.2
    max_range: 4.5
    i2c_address: 1
  - name: '/sensors/right_sonar'
    frame_id: '/right_sonar'
    radiation_type: 0
    field_of_view: 80.0
    min_range: 0.2
    max_range: 4.5
    i2c_address: 2
